// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.common.msg;

public final class BaseBean {
  private BaseBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.common.msg.BaseBean.cgPlayerCheckLogin);
    registry.add(com.common.msg.BaseBean.gcPlayerCheckLogin);
    registry.add(com.common.msg.BaseBean.cgGetRoleList);
    registry.add(com.common.msg.BaseBean.gcGetRoleList);
    registry.add(com.common.msg.BaseBean.cgCreateRole);
    registry.add(com.common.msg.BaseBean.gcCreateRole);
    registry.add(com.common.msg.BaseBean.cgSelectRole);
    registry.add(com.common.msg.BaseBean.cgRoleReName);
    registry.add(com.common.msg.BaseBean.gcRoleReName);
    registry.add(com.common.msg.BaseBean.cgEnterScene);
    registry.add(com.common.msg.BaseBean.gcEnterScene);
    registry.add(com.common.msg.BaseBean.gcRoleSymbolChangedInt);
    registry.add(com.common.msg.BaseBean.gcGetBuildList);
    registry.add(com.common.msg.BaseBean.cgCreatBuild);
    registry.add(com.common.msg.BaseBean.cgQuickBuild);
    registry.add(com.common.msg.BaseBean.cgBreakBuild);
    registry.add(com.common.msg.BaseBean.gcUpdateBuildData);
    registry.add(com.common.msg.BaseBean.gcUpdateBuildIngData);
    registry.add(com.common.msg.BaseBean.missionInfo);
    registry.add(com.common.msg.BaseBean.missionReward);
  }
  public interface BaseMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<BaseMessage> {

    // required .bean.BaseMessage.Type type = 1;
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    com.common.msg.BaseBean.BaseMessage.Type getType();

    // required .bean.BaseMessage.MessageCode messageCode = 2;
    /**
     * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
     */
    boolean hasMessageCode();
    /**
     * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
     */
    com.common.msg.BaseBean.BaseMessage.MessageCode getMessageCode();
  }
  /**
   * Protobuf type {@code bean.BaseMessage}
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        BaseMessage> implements BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.common.msg.BaseBean.BaseMessage, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.common.msg.BaseBean.BaseMessage.Type value = com.common.msg.BaseBean.BaseMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.common.msg.BaseBean.BaseMessage.MessageCode value = com.common.msg.BaseBean.BaseMessage.MessageCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.BaseBean.internal_static_bean_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.BaseBean.internal_static_bean_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.BaseBean.BaseMessage.class, com.common.msg.BaseBean.BaseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code bean.BaseMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GLOBALMESSAGE = 1;</code>
       */
      GLOBALMESSAGE(0, 1),
      /**
       * <code>PLAYERMESSAGE = 2;</code>
       */
      PLAYERMESSAGE(1, 2),
      ;

      /**
       * <code>GLOBALMESSAGE = 1;</code>
       */
      public static final int GLOBALMESSAGE_VALUE = 1;
      /**
       * <code>PLAYERMESSAGE = 2;</code>
       */
      public static final int PLAYERMESSAGE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return GLOBALMESSAGE;
          case 2: return PLAYERMESSAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.common.msg.BaseBean.BaseMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:bean.BaseMessage.Type)
    }

    /**
     * Protobuf enum {@code bean.BaseMessage.MessageCode}
     */
    public enum MessageCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CGPLAYERCHECKLOGIN = 1;</code>
       */
      CGPLAYERCHECKLOGIN(0, 1),
      /**
       * <code>GCPLAYERCHECKLOGIN = 2;</code>
       */
      GCPLAYERCHECKLOGIN(1, 2),
      /**
       * <code>CGGETROLELIST = 3;</code>
       */
      CGGETROLELIST(2, 3),
      /**
       * <code>GCGETROLELIST = 4;</code>
       */
      GCGETROLELIST(3, 4),
      /**
       * <code>CGCREATEROLE = 5;</code>
       */
      CGCREATEROLE(4, 5),
      /**
       * <code>GCCREATEROLE = 6;</code>
       */
      GCCREATEROLE(5, 6),
      /**
       * <code>CGSELECTROLE = 7;</code>
       */
      CGSELECTROLE(6, 7),
      /**
       * <code>CGROLERENAME = 8;</code>
       */
      CGROLERENAME(7, 8),
      /**
       * <code>GCROLERENAME = 9;</code>
       */
      GCROLERENAME(8, 9),
      /**
       * <code>CGENTERSCENE = 10;</code>
       */
      CGENTERSCENE(9, 10),
      /**
       * <code>GCENTERSCENE = 11;</code>
       */
      GCENTERSCENE(10, 11),
      /**
       * <code>GCROLESYMBOLCHANGEDINT = 12;</code>
       */
      GCROLESYMBOLCHANGEDINT(11, 12),
      /**
       * <code>GCGETBUILDLIST = 13;</code>
       */
      GCGETBUILDLIST(12, 13),
      /**
       * <code>CGCREATBUILD = 14;</code>
       */
      CGCREATBUILD(13, 14),
      /**
       * <code>CGQUICKBUILD = 15;</code>
       */
      CGQUICKBUILD(14, 15),
      /**
       * <code>CGBREAKBUILD = 16;</code>
       */
      CGBREAKBUILD(15, 16),
      /**
       * <code>GCUPDATEBUILDDATA = 17;</code>
       */
      GCUPDATEBUILDDATA(16, 17),
      /**
       * <code>GCUPDATEBUILDINGDATA = 18;</code>
       */
      GCUPDATEBUILDINGDATA(17, 18),
      /**
       * <code>MISSIONINFO = 19;</code>
       */
      MISSIONINFO(18, 19),
      /**
       * <code>MISSIONREWARD = 20;</code>
       */
      MISSIONREWARD(19, 20),
      ;

      /**
       * <code>CGPLAYERCHECKLOGIN = 1;</code>
       */
      public static final int CGPLAYERCHECKLOGIN_VALUE = 1;
      /**
       * <code>GCPLAYERCHECKLOGIN = 2;</code>
       */
      public static final int GCPLAYERCHECKLOGIN_VALUE = 2;
      /**
       * <code>CGGETROLELIST = 3;</code>
       */
      public static final int CGGETROLELIST_VALUE = 3;
      /**
       * <code>GCGETROLELIST = 4;</code>
       */
      public static final int GCGETROLELIST_VALUE = 4;
      /**
       * <code>CGCREATEROLE = 5;</code>
       */
      public static final int CGCREATEROLE_VALUE = 5;
      /**
       * <code>GCCREATEROLE = 6;</code>
       */
      public static final int GCCREATEROLE_VALUE = 6;
      /**
       * <code>CGSELECTROLE = 7;</code>
       */
      public static final int CGSELECTROLE_VALUE = 7;
      /**
       * <code>CGROLERENAME = 8;</code>
       */
      public static final int CGROLERENAME_VALUE = 8;
      /**
       * <code>GCROLERENAME = 9;</code>
       */
      public static final int GCROLERENAME_VALUE = 9;
      /**
       * <code>CGENTERSCENE = 10;</code>
       */
      public static final int CGENTERSCENE_VALUE = 10;
      /**
       * <code>GCENTERSCENE = 11;</code>
       */
      public static final int GCENTERSCENE_VALUE = 11;
      /**
       * <code>GCROLESYMBOLCHANGEDINT = 12;</code>
       */
      public static final int GCROLESYMBOLCHANGEDINT_VALUE = 12;
      /**
       * <code>GCGETBUILDLIST = 13;</code>
       */
      public static final int GCGETBUILDLIST_VALUE = 13;
      /**
       * <code>CGCREATBUILD = 14;</code>
       */
      public static final int CGCREATBUILD_VALUE = 14;
      /**
       * <code>CGQUICKBUILD = 15;</code>
       */
      public static final int CGQUICKBUILD_VALUE = 15;
      /**
       * <code>CGBREAKBUILD = 16;</code>
       */
      public static final int CGBREAKBUILD_VALUE = 16;
      /**
       * <code>GCUPDATEBUILDDATA = 17;</code>
       */
      public static final int GCUPDATEBUILDDATA_VALUE = 17;
      /**
       * <code>GCUPDATEBUILDINGDATA = 18;</code>
       */
      public static final int GCUPDATEBUILDINGDATA_VALUE = 18;
      /**
       * <code>MISSIONINFO = 19;</code>
       */
      public static final int MISSIONINFO_VALUE = 19;
      /**
       * <code>MISSIONREWARD = 20;</code>
       */
      public static final int MISSIONREWARD_VALUE = 20;


      public final int getNumber() { return value; }

      public static MessageCode valueOf(int value) {
        switch (value) {
          case 1: return CGPLAYERCHECKLOGIN;
          case 2: return GCPLAYERCHECKLOGIN;
          case 3: return CGGETROLELIST;
          case 4: return GCGETROLELIST;
          case 5: return CGCREATEROLE;
          case 6: return GCCREATEROLE;
          case 7: return CGSELECTROLE;
          case 8: return CGROLERENAME;
          case 9: return GCROLERENAME;
          case 10: return CGENTERSCENE;
          case 11: return GCENTERSCENE;
          case 12: return GCROLESYMBOLCHANGEDINT;
          case 13: return GCGETBUILDLIST;
          case 14: return CGCREATBUILD;
          case 15: return CGQUICKBUILD;
          case 16: return CGBREAKBUILD;
          case 17: return GCUPDATEBUILDDATA;
          case 18: return GCUPDATEBUILDINGDATA;
          case 19: return MISSIONINFO;
          case 20: return MISSIONREWARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageCode>() {
              public MessageCode findValueByNumber(int number) {
                return MessageCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.common.msg.BaseBean.BaseMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final MessageCode[] VALUES = values();

      public static MessageCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:bean.BaseMessage.MessageCode)
    }

    private int bitField0_;
    // required .bean.BaseMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.common.msg.BaseBean.BaseMessage.Type type_;
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    public com.common.msg.BaseBean.BaseMessage.Type getType() {
      return type_;
    }

    // required .bean.BaseMessage.MessageCode messageCode = 2;
    public static final int MESSAGECODE_FIELD_NUMBER = 2;
    private com.common.msg.BaseBean.BaseMessage.MessageCode messageCode_;
    /**
     * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
     */
    public boolean hasMessageCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
     */
    public com.common.msg.BaseBean.BaseMessage.MessageCode getMessageCode() {
      return messageCode_;
    }

    private void initFields() {
      type_ = com.common.msg.BaseBean.BaseMessage.Type.GLOBALMESSAGE;
      messageCode_ = com.common.msg.BaseBean.BaseMessage.MessageCode.CGPLAYERCHECKLOGIN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.common.msg.BaseBean.BaseMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageCode_.getNumber());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageCode_.getNumber());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.BaseBean.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.BaseBean.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.BaseBean.BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.common.msg.BaseBean.BaseMessage, Builder> implements com.common.msg.BaseBean.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.BaseBean.internal_static_bean_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.BaseBean.internal_static_bean_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.BaseBean.BaseMessage.class, com.common.msg.BaseBean.BaseMessage.Builder.class);
      }

      // Construct using com.common.msg.BaseBean.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.common.msg.BaseBean.BaseMessage.Type.GLOBALMESSAGE;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageCode_ = com.common.msg.BaseBean.BaseMessage.MessageCode.CGPLAYERCHECKLOGIN;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.BaseBean.internal_static_bean_BaseMessage_descriptor;
      }

      public com.common.msg.BaseBean.BaseMessage getDefaultInstanceForType() {
        return com.common.msg.BaseBean.BaseMessage.getDefaultInstance();
      }

      public com.common.msg.BaseBean.BaseMessage build() {
        com.common.msg.BaseBean.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.BaseBean.BaseMessage buildPartial() {
        com.common.msg.BaseBean.BaseMessage result = new com.common.msg.BaseBean.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageCode_ = messageCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.BaseBean.BaseMessage) {
          return mergeFrom((com.common.msg.BaseBean.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.BaseBean.BaseMessage other) {
        if (other == com.common.msg.BaseBean.BaseMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMessageCode()) {
          setMessageCode(other.getMessageCode());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasMessageCode()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.BaseBean.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.BaseBean.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .bean.BaseMessage.Type type = 1;
      private com.common.msg.BaseBean.BaseMessage.Type type_ = com.common.msg.BaseBean.BaseMessage.Type.GLOBALMESSAGE;
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public com.common.msg.BaseBean.BaseMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public Builder setType(com.common.msg.BaseBean.BaseMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.common.msg.BaseBean.BaseMessage.Type.GLOBALMESSAGE;
        onChanged();
        return this;
      }

      // required .bean.BaseMessage.MessageCode messageCode = 2;
      private com.common.msg.BaseBean.BaseMessage.MessageCode messageCode_ = com.common.msg.BaseBean.BaseMessage.MessageCode.CGPLAYERCHECKLOGIN;
      /**
       * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
       */
      public boolean hasMessageCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
       */
      public com.common.msg.BaseBean.BaseMessage.MessageCode getMessageCode() {
        return messageCode_;
      }
      /**
       * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
       */
      public Builder setMessageCode(com.common.msg.BaseBean.BaseMessage.MessageCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .bean.BaseMessage.MessageCode messageCode = 2;</code>
       */
      public Builder clearMessageCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageCode_ = com.common.msg.BaseBean.BaseMessage.MessageCode.CGPLAYERCHECKLOGIN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.BaseMessage)
  }

  public static final int CGPLAYERCHECKLOGIN_FIELD_NUMBER = 100;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.CGPlayerCheckLogin> cgPlayerCheckLogin = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.CGPlayerCheckLogin.class,
        com.common.msg.PlayerBean.CGPlayerCheckLogin.getDefaultInstance());
  public static final int GCPLAYERCHECKLOGIN_FIELD_NUMBER = 101;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.GCPlayerCheckLogin> gcPlayerCheckLogin = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.GCPlayerCheckLogin.class,
        com.common.msg.PlayerBean.GCPlayerCheckLogin.getDefaultInstance());
  public static final int CGGETROLELIST_FIELD_NUMBER = 102;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.CGGetRoleList> cgGetRoleList = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.CGGetRoleList.class,
        com.common.msg.PlayerBean.CGGetRoleList.getDefaultInstance());
  public static final int GCGETROLELIST_FIELD_NUMBER = 103;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.GCGetRoleList> gcGetRoleList = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.GCGetRoleList.class,
        com.common.msg.PlayerBean.GCGetRoleList.getDefaultInstance());
  public static final int CGCREATEROLE_FIELD_NUMBER = 104;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.CGCreateRole> cgCreateRole = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.CGCreateRole.class,
        com.common.msg.PlayerBean.CGCreateRole.getDefaultInstance());
  public static final int GCCREATEROLE_FIELD_NUMBER = 105;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.GCCreateRole> gcCreateRole = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.GCCreateRole.class,
        com.common.msg.PlayerBean.GCCreateRole.getDefaultInstance());
  public static final int CGSELECTROLE_FIELD_NUMBER = 106;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.CGSelectRole> cgSelectRole = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.CGSelectRole.class,
        com.common.msg.PlayerBean.CGSelectRole.getDefaultInstance());
  public static final int CGROLERENAME_FIELD_NUMBER = 107;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.CGRoleReName> cgRoleReName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.CGRoleReName.class,
        com.common.msg.PlayerBean.CGRoleReName.getDefaultInstance());
  public static final int GCROLERENAME_FIELD_NUMBER = 108;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.GCRoleReName> gcRoleReName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.GCRoleReName.class,
        com.common.msg.PlayerBean.GCRoleReName.getDefaultInstance());
  public static final int CGENTERSCENE_FIELD_NUMBER = 109;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.CGEnterScene> cgEnterScene = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.CGEnterScene.class,
        com.common.msg.PlayerBean.CGEnterScene.getDefaultInstance());
  public static final int GCENTERSCENE_FIELD_NUMBER = 110;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.PlayerBean.GCEnterScene> gcEnterScene = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.PlayerBean.GCEnterScene.class,
        com.common.msg.PlayerBean.GCEnterScene.getDefaultInstance());
  public static final int GCROLESYMBOLCHANGEDINT_FIELD_NUMBER = 200;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.HumanBean.GCRoleSymbolChangedInt> gcRoleSymbolChangedInt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.HumanBean.GCRoleSymbolChangedInt.class,
        com.common.msg.HumanBean.GCRoleSymbolChangedInt.getDefaultInstance());
  public static final int GCGETBUILDLIST_FIELD_NUMBER = 300;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.BuildBean.GCGetBuildList> gcGetBuildList = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.BuildBean.GCGetBuildList.class,
        com.common.msg.BuildBean.GCGetBuildList.getDefaultInstance());
  public static final int CGCREATBUILD_FIELD_NUMBER = 301;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.BuildBean.CGCreatBuild> cgCreatBuild = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.BuildBean.CGCreatBuild.class,
        com.common.msg.BuildBean.CGCreatBuild.getDefaultInstance());
  public static final int CGQUICKBUILD_FIELD_NUMBER = 302;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.BuildBean.CGQuickBuild> cgQuickBuild = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.BuildBean.CGQuickBuild.class,
        com.common.msg.BuildBean.CGQuickBuild.getDefaultInstance());
  public static final int CGBREAKBUILD_FIELD_NUMBER = 303;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.BuildBean.CGBreakBuild> cgBreakBuild = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.BuildBean.CGBreakBuild.class,
        com.common.msg.BuildBean.CGBreakBuild.getDefaultInstance());
  public static final int GCUPDATEBUILDDATA_FIELD_NUMBER = 304;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.BuildBean.GCUpdateBuildData> gcUpdateBuildData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.BuildBean.GCUpdateBuildData.class,
        com.common.msg.BuildBean.GCUpdateBuildData.getDefaultInstance());
  public static final int GCUPDATEBUILDINGDATA_FIELD_NUMBER = 305;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.BuildBean.GCUpdateBuildIngData> gcUpdateBuildIngData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.BuildBean.GCUpdateBuildIngData.class,
        com.common.msg.BuildBean.GCUpdateBuildIngData.getDefaultInstance());
  public static final int MISSIONINFO_FIELD_NUMBER = 400;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.MissionBean.MissionInfo> missionInfo = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.MissionBean.MissionInfo.class,
        com.common.msg.MissionBean.MissionInfo.getDefaultInstance());
  public static final int MISSIONREWARD_FIELD_NUMBER = 401;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.BaseBean.BaseMessage,
      com.common.msg.MissionBean.MissionReward> missionReward = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.MissionBean.MissionReward.class,
        com.common.msg.MissionBean.MissionReward.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_BaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\004bean\032\rmission.proto\032\014pl" +
      "ayer.proto\032\013human.proto\032\013build.proto\"\276\004\n" +
      "\013BaseMessage\022$\n\004type\030\001 \002(\0162\026.bean.BaseMe" +
      "ssage.Type\0222\n\013messageCode\030\002 \002(\0162\035.bean.B" +
      "aseMessage.MessageCode\",\n\004Type\022\021\n\rGLOBAL" +
      "MESSAGE\020\001\022\021\n\rPLAYERMESSAGE\020\002\"\234\003\n\013Message" +
      "Code\022\026\n\022CGPLAYERCHECKLOGIN\020\001\022\026\n\022GCPLAYER" +
      "CHECKLOGIN\020\002\022\021\n\rCGGETROLELIST\020\003\022\021\n\rGCGET" +
      "ROLELIST\020\004\022\020\n\014CGCREATEROLE\020\005\022\020\n\014GCCREATE" +
      "ROLE\020\006\022\020\n\014CGSELECTROLE\020\007\022\020\n\014CGROLERENAME",
      "\020\010\022\020\n\014GCROLERENAME\020\t\022\020\n\014CGENTERSCENE\020\n\022\020" +
      "\n\014GCENTERSCENE\020\013\022\032\n\026GCROLESYMBOLCHANGEDI" +
      "NT\020\014\022\022\n\016GCGETBUILDLIST\020\r\022\020\n\014CGCREATBUILD" +
      "\020\016\022\020\n\014CGQUICKBUILD\020\017\022\020\n\014CGBREAKBUILD\020\020\022\025" +
      "\n\021GCUPDATEBUILDDATA\020\021\022\030\n\024GCUPDATEBUILDIN" +
      "GDATA\020\022\022\017\n\013MISSIONINFO\020\023\022\021\n\rMISSIONREWAR" +
      "D\020\024*\010\010d\020\200\200\200\200\002:G\n\022cgPlayerCheckLogin\022\021.be" +
      "an.BaseMessage\030d \001(\0132\030.bean.CGPlayerChec" +
      "kLogin:G\n\022gcPlayerCheckLogin\022\021.bean.Base" +
      "Message\030e \001(\0132\030.bean.GCPlayerCheckLogin:",
      "=\n\rcgGetRoleList\022\021.bean.BaseMessage\030f \001(" +
      "\0132\023.bean.CGGetRoleList:=\n\rgcGetRoleList\022" +
      "\021.bean.BaseMessage\030g \001(\0132\023.bean.GCGetRol" +
      "eList:;\n\014cgCreateRole\022\021.bean.BaseMessage" +
      "\030h \001(\0132\022.bean.CGCreateRole:;\n\014gcCreateRo" +
      "le\022\021.bean.BaseMessage\030i \001(\0132\022.bean.GCCre" +
      "ateRole:;\n\014cgSelectRole\022\021.bean.BaseMessa" +
      "ge\030j \001(\0132\022.bean.CGSelectRole:;\n\014cgRoleRe" +
      "Name\022\021.bean.BaseMessage\030k \001(\0132\022.bean.CGR" +
      "oleReName:;\n\014gcRoleReName\022\021.bean.BaseMes",
      "sage\030l \001(\0132\022.bean.GCRoleReName:;\n\014cgEnte" +
      "rScene\022\021.bean.BaseMessage\030m \001(\0132\022.bean.C" +
      "GEnterScene:;\n\014gcEnterScene\022\021.bean.BaseM" +
      "essage\030n \001(\0132\022.bean.GCEnterScene:P\n\026gcRo" +
      "leSymbolChangedInt\022\021.bean.BaseMessage\030\310\001" +
      " \001(\0132\034.bean.GCRoleSymbolChangedInt:@\n\016gc" +
      "GetBuildList\022\021.bean.BaseMessage\030\254\002 \001(\0132\024" +
      ".bean.GCGetBuildList:<\n\014cgCreatBuild\022\021.b" +
      "ean.BaseMessage\030\255\002 \001(\0132\022.bean.CGCreatBui" +
      "ld:<\n\014cgQuickBuild\022\021.bean.BaseMessage\030\256\002",
      " \001(\0132\022.bean.CGQuickBuild:<\n\014cgBreakBuild" +
      "\022\021.bean.BaseMessage\030\257\002 \001(\0132\022.bean.CGBrea" +
      "kBuild:F\n\021gcUpdateBuildData\022\021.bean.BaseM" +
      "essage\030\260\002 \001(\0132\027.bean.GCUpdateBuildData:L" +
      "\n\024gcUpdateBuildIngData\022\021.bean.BaseMessag" +
      "e\030\261\002 \001(\0132\032.bean.GCUpdateBuildIngData::\n\013" +
      "missionInfo\022\021.bean.BaseMessage\030\220\003 \001(\0132\021." +
      "bean.MissionInfo:>\n\rmissionReward\022\021.bean" +
      ".BaseMessage\030\221\003 \001(\0132\023.bean.MissionReward" +
      "B\032\n\016com.common.msgB\010BaseBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bean_BaseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bean_BaseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_BaseMessage_descriptor,
              new java.lang.String[] { "Type", "MessageCode", });
          cgPlayerCheckLogin.internalInit(descriptor.getExtensions().get(0));
          gcPlayerCheckLogin.internalInit(descriptor.getExtensions().get(1));
          cgGetRoleList.internalInit(descriptor.getExtensions().get(2));
          gcGetRoleList.internalInit(descriptor.getExtensions().get(3));
          cgCreateRole.internalInit(descriptor.getExtensions().get(4));
          gcCreateRole.internalInit(descriptor.getExtensions().get(5));
          cgSelectRole.internalInit(descriptor.getExtensions().get(6));
          cgRoleReName.internalInit(descriptor.getExtensions().get(7));
          gcRoleReName.internalInit(descriptor.getExtensions().get(8));
          cgEnterScene.internalInit(descriptor.getExtensions().get(9));
          gcEnterScene.internalInit(descriptor.getExtensions().get(10));
          gcRoleSymbolChangedInt.internalInit(descriptor.getExtensions().get(11));
          gcGetBuildList.internalInit(descriptor.getExtensions().get(12));
          cgCreatBuild.internalInit(descriptor.getExtensions().get(13));
          cgQuickBuild.internalInit(descriptor.getExtensions().get(14));
          cgBreakBuild.internalInit(descriptor.getExtensions().get(15));
          gcUpdateBuildData.internalInit(descriptor.getExtensions().get(16));
          gcUpdateBuildIngData.internalInit(descriptor.getExtensions().get(17));
          missionInfo.internalInit(descriptor.getExtensions().get(18));
          missionReward.internalInit(descriptor.getExtensions().get(19));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.common.msg.MissionBean.getDescriptor(),
          com.common.msg.PlayerBean.getDescriptor(),
          com.common.msg.HumanBean.getDescriptor(),
          com.common.msg.BuildBean.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
