// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: human.proto

package com.common.msg;

public final class HumanBean {
  private HumanBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GCRoleSymbolChangedIntOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 type = 1;
    /**
     * <code>required int64 type = 1;</code>
     *
     * <pre>
     *属性值的类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int64 type = 1;</code>
     *
     * <pre>
     *属性值的类型
     * </pre>
     */
    long getType();

    // required int64 roleId = 2;
    /**
     * <code>required int64 roleId = 2;</code>
     */
    boolean hasRoleId();
    /**
     * <code>required int64 roleId = 2;</code>
     */
    long getRoleId();

    // repeated .bean.KeyValueData keyValueData = 3;
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    java.util.List<com.common.msg.HumanBean.KeyValueData> 
        getKeyValueDataList();
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    com.common.msg.HumanBean.KeyValueData getKeyValueData(int index);
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    int getKeyValueDataCount();
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    java.util.List<? extends com.common.msg.HumanBean.KeyValueDataOrBuilder> 
        getKeyValueDataOrBuilderList();
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    com.common.msg.HumanBean.KeyValueDataOrBuilder getKeyValueDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bean.GCRoleSymbolChangedInt}
   */
  public static final class GCRoleSymbolChangedInt extends
      com.google.protobuf.GeneratedMessage
      implements GCRoleSymbolChangedIntOrBuilder {
    // Use GCRoleSymbolChangedInt.newBuilder() to construct.
    private GCRoleSymbolChangedInt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCRoleSymbolChangedInt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCRoleSymbolChangedInt defaultInstance;
    public static GCRoleSymbolChangedInt getDefaultInstance() {
      return defaultInstance;
    }

    public GCRoleSymbolChangedInt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCRoleSymbolChangedInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roleId_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                keyValueData_ = new java.util.ArrayList<com.common.msg.HumanBean.KeyValueData>();
                mutable_bitField0_ |= 0x00000004;
              }
              keyValueData_.add(input.readMessage(com.common.msg.HumanBean.KeyValueData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          keyValueData_ = java.util.Collections.unmodifiableList(keyValueData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.HumanBean.internal_static_bean_GCRoleSymbolChangedInt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.HumanBean.internal_static_bean_GCRoleSymbolChangedInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.HumanBean.GCRoleSymbolChangedInt.class, com.common.msg.HumanBean.GCRoleSymbolChangedInt.Builder.class);
    }

    public static com.google.protobuf.Parser<GCRoleSymbolChangedInt> PARSER =
        new com.google.protobuf.AbstractParser<GCRoleSymbolChangedInt>() {
      public GCRoleSymbolChangedInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCRoleSymbolChangedInt(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCRoleSymbolChangedInt> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private long type_;
    /**
     * <code>required int64 type = 1;</code>
     *
     * <pre>
     *属性值的类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 type = 1;</code>
     *
     * <pre>
     *属性值的类型
     * </pre>
     */
    public long getType() {
      return type_;
    }

    // required int64 roleId = 2;
    public static final int ROLEID_FIELD_NUMBER = 2;
    private long roleId_;
    /**
     * <code>required int64 roleId = 2;</code>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 roleId = 2;</code>
     */
    public long getRoleId() {
      return roleId_;
    }

    // repeated .bean.KeyValueData keyValueData = 3;
    public static final int KEYVALUEDATA_FIELD_NUMBER = 3;
    private java.util.List<com.common.msg.HumanBean.KeyValueData> keyValueData_;
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    public java.util.List<com.common.msg.HumanBean.KeyValueData> getKeyValueDataList() {
      return keyValueData_;
    }
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    public java.util.List<? extends com.common.msg.HumanBean.KeyValueDataOrBuilder> 
        getKeyValueDataOrBuilderList() {
      return keyValueData_;
    }
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    public int getKeyValueDataCount() {
      return keyValueData_.size();
    }
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    public com.common.msg.HumanBean.KeyValueData getKeyValueData(int index) {
      return keyValueData_.get(index);
    }
    /**
     * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
     */
    public com.common.msg.HumanBean.KeyValueDataOrBuilder getKeyValueDataOrBuilder(
        int index) {
      return keyValueData_.get(index);
    }

    private void initFields() {
      type_ = 0L;
      roleId_ = 0L;
      keyValueData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getKeyValueDataCount(); i++) {
        if (!getKeyValueData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, roleId_);
      }
      for (int i = 0; i < keyValueData_.size(); i++) {
        output.writeMessage(3, keyValueData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, roleId_);
      }
      for (int i = 0; i < keyValueData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, keyValueData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.HumanBean.GCRoleSymbolChangedInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.HumanBean.GCRoleSymbolChangedInt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.GCRoleSymbolChangedInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.common.msg.HumanBean.GCRoleSymbolChangedIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.HumanBean.internal_static_bean_GCRoleSymbolChangedInt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.HumanBean.internal_static_bean_GCRoleSymbolChangedInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.HumanBean.GCRoleSymbolChangedInt.class, com.common.msg.HumanBean.GCRoleSymbolChangedInt.Builder.class);
      }

      // Construct using com.common.msg.HumanBean.GCRoleSymbolChangedInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKeyValueDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        roleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (keyValueDataBuilder_ == null) {
          keyValueData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          keyValueDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.HumanBean.internal_static_bean_GCRoleSymbolChangedInt_descriptor;
      }

      public com.common.msg.HumanBean.GCRoleSymbolChangedInt getDefaultInstanceForType() {
        return com.common.msg.HumanBean.GCRoleSymbolChangedInt.getDefaultInstance();
      }

      public com.common.msg.HumanBean.GCRoleSymbolChangedInt build() {
        com.common.msg.HumanBean.GCRoleSymbolChangedInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.HumanBean.GCRoleSymbolChangedInt buildPartial() {
        com.common.msg.HumanBean.GCRoleSymbolChangedInt result = new com.common.msg.HumanBean.GCRoleSymbolChangedInt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roleId_ = roleId_;
        if (keyValueDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            keyValueData_ = java.util.Collections.unmodifiableList(keyValueData_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.keyValueData_ = keyValueData_;
        } else {
          result.keyValueData_ = keyValueDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.HumanBean.GCRoleSymbolChangedInt) {
          return mergeFrom((com.common.msg.HumanBean.GCRoleSymbolChangedInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.HumanBean.GCRoleSymbolChangedInt other) {
        if (other == com.common.msg.HumanBean.GCRoleSymbolChangedInt.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (keyValueDataBuilder_ == null) {
          if (!other.keyValueData_.isEmpty()) {
            if (keyValueData_.isEmpty()) {
              keyValueData_ = other.keyValueData_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureKeyValueDataIsMutable();
              keyValueData_.addAll(other.keyValueData_);
            }
            onChanged();
          }
        } else {
          if (!other.keyValueData_.isEmpty()) {
            if (keyValueDataBuilder_.isEmpty()) {
              keyValueDataBuilder_.dispose();
              keyValueDataBuilder_ = null;
              keyValueData_ = other.keyValueData_;
              bitField0_ = (bitField0_ & ~0x00000004);
              keyValueDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKeyValueDataFieldBuilder() : null;
            } else {
              keyValueDataBuilder_.addAllMessages(other.keyValueData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasRoleId()) {
          
          return false;
        }
        for (int i = 0; i < getKeyValueDataCount(); i++) {
          if (!getKeyValueData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.HumanBean.GCRoleSymbolChangedInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.HumanBean.GCRoleSymbolChangedInt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 type = 1;
      private long type_ ;
      /**
       * <code>required int64 type = 1;</code>
       *
       * <pre>
       *属性值的类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 type = 1;</code>
       *
       * <pre>
       *属性值的类型
       * </pre>
       */
      public long getType() {
        return type_;
      }
      /**
       * <code>required int64 type = 1;</code>
       *
       * <pre>
       *属性值的类型
       * </pre>
       */
      public Builder setType(long value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 type = 1;</code>
       *
       * <pre>
       *属性值的类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0L;
        onChanged();
        return this;
      }

      // required int64 roleId = 2;
      private long roleId_ ;
      /**
       * <code>required int64 roleId = 2;</code>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 roleId = 2;</code>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>required int64 roleId = 2;</code>
       */
      public Builder setRoleId(long value) {
        bitField0_ |= 0x00000002;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roleId = 2;</code>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roleId_ = 0L;
        onChanged();
        return this;
      }

      // repeated .bean.KeyValueData keyValueData = 3;
      private java.util.List<com.common.msg.HumanBean.KeyValueData> keyValueData_ =
        java.util.Collections.emptyList();
      private void ensureKeyValueDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          keyValueData_ = new java.util.ArrayList<com.common.msg.HumanBean.KeyValueData>(keyValueData_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.common.msg.HumanBean.KeyValueData, com.common.msg.HumanBean.KeyValueData.Builder, com.common.msg.HumanBean.KeyValueDataOrBuilder> keyValueDataBuilder_;

      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public java.util.List<com.common.msg.HumanBean.KeyValueData> getKeyValueDataList() {
        if (keyValueDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keyValueData_);
        } else {
          return keyValueDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public int getKeyValueDataCount() {
        if (keyValueDataBuilder_ == null) {
          return keyValueData_.size();
        } else {
          return keyValueDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public com.common.msg.HumanBean.KeyValueData getKeyValueData(int index) {
        if (keyValueDataBuilder_ == null) {
          return keyValueData_.get(index);
        } else {
          return keyValueDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder setKeyValueData(
          int index, com.common.msg.HumanBean.KeyValueData value) {
        if (keyValueDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyValueDataIsMutable();
          keyValueData_.set(index, value);
          onChanged();
        } else {
          keyValueDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder setKeyValueData(
          int index, com.common.msg.HumanBean.KeyValueData.Builder builderForValue) {
        if (keyValueDataBuilder_ == null) {
          ensureKeyValueDataIsMutable();
          keyValueData_.set(index, builderForValue.build());
          onChanged();
        } else {
          keyValueDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder addKeyValueData(com.common.msg.HumanBean.KeyValueData value) {
        if (keyValueDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyValueDataIsMutable();
          keyValueData_.add(value);
          onChanged();
        } else {
          keyValueDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder addKeyValueData(
          int index, com.common.msg.HumanBean.KeyValueData value) {
        if (keyValueDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyValueDataIsMutable();
          keyValueData_.add(index, value);
          onChanged();
        } else {
          keyValueDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder addKeyValueData(
          com.common.msg.HumanBean.KeyValueData.Builder builderForValue) {
        if (keyValueDataBuilder_ == null) {
          ensureKeyValueDataIsMutable();
          keyValueData_.add(builderForValue.build());
          onChanged();
        } else {
          keyValueDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder addKeyValueData(
          int index, com.common.msg.HumanBean.KeyValueData.Builder builderForValue) {
        if (keyValueDataBuilder_ == null) {
          ensureKeyValueDataIsMutable();
          keyValueData_.add(index, builderForValue.build());
          onChanged();
        } else {
          keyValueDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder addAllKeyValueData(
          java.lang.Iterable<? extends com.common.msg.HumanBean.KeyValueData> values) {
        if (keyValueDataBuilder_ == null) {
          ensureKeyValueDataIsMutable();
          super.addAll(values, keyValueData_);
          onChanged();
        } else {
          keyValueDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder clearKeyValueData() {
        if (keyValueDataBuilder_ == null) {
          keyValueData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          keyValueDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public Builder removeKeyValueData(int index) {
        if (keyValueDataBuilder_ == null) {
          ensureKeyValueDataIsMutable();
          keyValueData_.remove(index);
          onChanged();
        } else {
          keyValueDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public com.common.msg.HumanBean.KeyValueData.Builder getKeyValueDataBuilder(
          int index) {
        return getKeyValueDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public com.common.msg.HumanBean.KeyValueDataOrBuilder getKeyValueDataOrBuilder(
          int index) {
        if (keyValueDataBuilder_ == null) {
          return keyValueData_.get(index);  } else {
          return keyValueDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public java.util.List<? extends com.common.msg.HumanBean.KeyValueDataOrBuilder> 
           getKeyValueDataOrBuilderList() {
        if (keyValueDataBuilder_ != null) {
          return keyValueDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keyValueData_);
        }
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public com.common.msg.HumanBean.KeyValueData.Builder addKeyValueDataBuilder() {
        return getKeyValueDataFieldBuilder().addBuilder(
            com.common.msg.HumanBean.KeyValueData.getDefaultInstance());
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public com.common.msg.HumanBean.KeyValueData.Builder addKeyValueDataBuilder(
          int index) {
        return getKeyValueDataFieldBuilder().addBuilder(
            index, com.common.msg.HumanBean.KeyValueData.getDefaultInstance());
      }
      /**
       * <code>repeated .bean.KeyValueData keyValueData = 3;</code>
       */
      public java.util.List<com.common.msg.HumanBean.KeyValueData.Builder> 
           getKeyValueDataBuilderList() {
        return getKeyValueDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.common.msg.HumanBean.KeyValueData, com.common.msg.HumanBean.KeyValueData.Builder, com.common.msg.HumanBean.KeyValueDataOrBuilder> 
          getKeyValueDataFieldBuilder() {
        if (keyValueDataBuilder_ == null) {
          keyValueDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.common.msg.HumanBean.KeyValueData, com.common.msg.HumanBean.KeyValueData.Builder, com.common.msg.HumanBean.KeyValueDataOrBuilder>(
                  keyValueData_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          keyValueData_ = null;
        }
        return keyValueDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:bean.GCRoleSymbolChangedInt)
    }

    static {
      defaultInstance = new GCRoleSymbolChangedInt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.GCRoleSymbolChangedInt)
  }

  public interface KeyValueDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 key = 1 [default = 1];
    /**
     * <code>required int32 key = 1 [default = 1];</code>
     *
     * <pre>
     *属性key
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required int32 key = 1 [default = 1];</code>
     *
     * <pre>
     *属性key
     * </pre>
     */
    int getKey();

    // required int32 value = 2 [default = 1];
    /**
     * <code>required int32 value = 2 [default = 1];</code>
     *
     * <pre>
     *属性值
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 2 [default = 1];</code>
     *
     * <pre>
     *属性值
     * </pre>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code bean.KeyValueData}
   */
  public static final class KeyValueData extends
      com.google.protobuf.GeneratedMessage
      implements KeyValueDataOrBuilder {
    // Use KeyValueData.newBuilder() to construct.
    private KeyValueData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValueData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValueData defaultInstance;
    public static KeyValueData getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValueData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              key_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.HumanBean.internal_static_bean_KeyValueData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.HumanBean.internal_static_bean_KeyValueData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.HumanBean.KeyValueData.class, com.common.msg.HumanBean.KeyValueData.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValueData> PARSER =
        new com.google.protobuf.AbstractParser<KeyValueData>() {
      public KeyValueData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValueData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValueData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 key = 1 [default = 1];
    public static final int KEY_FIELD_NUMBER = 1;
    private int key_;
    /**
     * <code>required int32 key = 1 [default = 1];</code>
     *
     * <pre>
     *属性key
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 key = 1 [default = 1];</code>
     *
     * <pre>
     *属性key
     * </pre>
     */
    public int getKey() {
      return key_;
    }

    // required int32 value = 2 [default = 1];
    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>required int32 value = 2 [default = 1];</code>
     *
     * <pre>
     *属性值
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 value = 2 [default = 1];</code>
     *
     * <pre>
     *属性值
     * </pre>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      key_ = 1;
      value_ = 1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.HumanBean.KeyValueData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.HumanBean.KeyValueData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.HumanBean.KeyValueData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.HumanBean.KeyValueData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.HumanBean.KeyValueData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.KeyValueData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.common.msg.HumanBean.KeyValueDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.HumanBean.internal_static_bean_KeyValueData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.HumanBean.internal_static_bean_KeyValueData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.HumanBean.KeyValueData.class, com.common.msg.HumanBean.KeyValueData.Builder.class);
      }

      // Construct using com.common.msg.HumanBean.KeyValueData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.HumanBean.internal_static_bean_KeyValueData_descriptor;
      }

      public com.common.msg.HumanBean.KeyValueData getDefaultInstanceForType() {
        return com.common.msg.HumanBean.KeyValueData.getDefaultInstance();
      }

      public com.common.msg.HumanBean.KeyValueData build() {
        com.common.msg.HumanBean.KeyValueData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.HumanBean.KeyValueData buildPartial() {
        com.common.msg.HumanBean.KeyValueData result = new com.common.msg.HumanBean.KeyValueData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.HumanBean.KeyValueData) {
          return mergeFrom((com.common.msg.HumanBean.KeyValueData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.HumanBean.KeyValueData other) {
        if (other == com.common.msg.HumanBean.KeyValueData.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.HumanBean.KeyValueData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.HumanBean.KeyValueData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 key = 1 [default = 1];
      private int key_ = 1;
      /**
       * <code>required int32 key = 1 [default = 1];</code>
       *
       * <pre>
       *属性key
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 key = 1 [default = 1];</code>
       *
       * <pre>
       *属性key
       * </pre>
       */
      public int getKey() {
        return key_;
      }
      /**
       * <code>required int32 key = 1 [default = 1];</code>
       *
       * <pre>
       *属性key
       * </pre>
       */
      public Builder setKey(int value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 key = 1 [default = 1];</code>
       *
       * <pre>
       *属性key
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 1;
        onChanged();
        return this;
      }

      // required int32 value = 2 [default = 1];
      private int value_ = 1;
      /**
       * <code>required int32 value = 2 [default = 1];</code>
       *
       * <pre>
       *属性值
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 value = 2 [default = 1];</code>
       *
       * <pre>
       *属性值
       * </pre>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 2 [default = 1];</code>
       *
       * <pre>
       *属性值
       * </pre>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 2 [default = 1];</code>
       *
       * <pre>
       *属性值
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.KeyValueData)
    }

    static {
      defaultInstance = new KeyValueData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.KeyValueData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_GCRoleSymbolChangedInt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_GCRoleSymbolChangedInt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_KeyValueData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_KeyValueData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013human.proto\022\004bean\"`\n\026GCRoleSymbolChang" +
      "edInt\022\014\n\004type\030\001 \002(\003\022\016\n\006roleId\030\002 \002(\003\022(\n\014k" +
      "eyValueData\030\003 \003(\0132\022.bean.KeyValueData\"0\n" +
      "\014KeyValueData\022\016\n\003key\030\001 \002(\005:\0011\022\020\n\005value\030\002" +
      " \002(\005:\0011B\033\n\016com.common.msgB\tHumanBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bean_GCRoleSymbolChangedInt_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bean_GCRoleSymbolChangedInt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_GCRoleSymbolChangedInt_descriptor,
              new java.lang.String[] { "Type", "RoleId", "KeyValueData", });
          internal_static_bean_KeyValueData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_bean_KeyValueData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_KeyValueData_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
